### ISSUE TITLE
Introduce a single access point

### ISSUE THREAD

**Issue by RhinosF1** [RhinosF1/PublicTestWiki-Inactive-Auto#10]
The script should run from a single file so it can be complied easier

**Comment by examknow** [comment]
How does an IRC front-end sound?

**Comment by RhinosF1** [comment]
> How does an IRC front-end sound?

No. Not secure enough.

**Comment by MacFan4000** [comment]
What about a single script with command line options like --remove and --notify?

So like python3 script.py --notify

**Comment by RhinosF1** [comment]
> What about a single script with command line options like --remove and --notify?
> 
> So like python3 script.py --notify

Fine by me

**Comment by examknow** [comment]
> 
> 
> What about a single script with command line options like --remove and --notify?
> 
> So like python3 script.py --notify

That was actually what I had in mind. I can work on that a little later as it could take some time.
