### ISSUE TITLE
Automate POST headers

### ISSUE THREAD

**Issue by RhinosF1** [RhinosF1/PublicTestWiki-Inactive-Auto#13]
User_agent = username@TestWikiAutoInactive <version>
Email = Email for the account logged into

Headers unavailable will use a default / not be added

**Comment by RhinosF1** [comment]
We need to manually ask on first load.

We should then save these and verify them based off the account.

We must include a contact info & name

**Comment by examknow** [comment]
> We should then save these and verify them based off the account.

How do we plan on saving and verifying the information? An sqlite database would be ideal for storage.

> We must include a contact info & name

Will this be done based on which user is using the script?

**Comment by RhinosF1** [comment]
> > We should then save these and verify them based off the account.
> 
> How do we plan on saving and verifying the information? An sqlite database would be ideal for storage.

Works for me
> > We must include a contact info & name
> 
> Will this be done based on which user is using the script?

Yes if logged in, last user if not or manually ask if never set before

**Comment by examknow** [comment]
> How do we plan on saving and verifying the information? An sqlite database would be ideal for storage.

Since the script will be ran locally on a user's machine, we should just have a config file that contains the user's information such as their email.

> How do we plan on saving and verifying the information?

I still do not know how we plan on verifying the information, why we would need to, or what information we would need to verify. Do you mean email addresses?

**Comment by RhinosF1** [comment]
Basic config file is fine and we verify the email given once they are logged in to the account they login in to
