### ISSUE TITLE
Repeated timeouts on action=userrights

### ISSUE THREAD

**Issue by RhinosF1** [RhinosF1/PublicTestWiki-Inactive-Auto#21]
The action=userrights api request is either instant or times out.

No clear reason why

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
>     response.begin()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 272, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
>     retries = retries.increment(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
>     raise value.with_traceback(tb)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
>     response.begin()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 272, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 153, in <module>
>     remove()
>   File "main.py", line 95, in remove
>     R = S.post(URL, data=PARAMS_4, headers=headers)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> <redacted>@<redacted> PublicTestWiki-Inactive-Auto-post-header-automation %

**Comment by examknow** [comment]
At first look, this seems to be a Miraheze/MediaWiki issue but I will look into the code as well.

**Comment by examknow** [comment]
I could not reproduce the error. The latest script just ran without any issues. Maybe try it again?

**Comment by RhinosF1** [comment]
blocking rc2 on it as it only occurs on #20

**Comment by RhinosF1** [comment]
Doesn’t seem to be us an happening on rc1
